language: node_js
env:
  global:
    CC_TEST_REPORTER_ID=$TRAVIS_BUILD_ID
node_js:
  - 7.6.0
services:
  - mongodb
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
